version: '3'

services:
  nginx:
    image: nginx:1.15.8
    container_name: 'nginx-container-dev'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ../../:/app
      - ../common/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm-service

  php-fpm-service:
    build:
      context: .
      dockerfile: php-fpm.docker
    working_dir: /app
    container_name: 'php-fpm-container-dev'
    ports:
      - '9000:9000'
    links:
      - postgres_db
    volumes:
      - ../../:/app
      - ../../uploads:/app/uploads
    environment:
      APP_ENV: "dev"

  postgres_db:
    image: postgres:10.6
    container_name: 'postgres-db-container-dev'
    restart: always
    ports:
      - '7778:5432'
    volumes:
      - postgres_data_volume_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: simple-note

volumes:
  postgres_data_volume_dev:
