jms_serializer:
  property_naming:
    id: 'jms_serializer.identical_property_naming_strategy'
  handlers:
    datetime:
      default_format: "U"
      default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default