vich_uploader:
  db_driver: orm # or mongodb or propel or phpcr

  mappings:
    event_picture:
      uri_prefix: /files/note_attachment
      upload_destination: '%kernel.project_dir%/uploads/note_attachment'
      inject_on_load: true
      delete_on_update: true
      delete_on_remove: true
      namer:            vich_uploader.namer_uniqid