# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    spool:
        type: 'file'
        path: '%kernel.project_dir%/var/spool'
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
